version: '3'

services:
  tapo-P110-exporter:
    image: p110-exporter
    volumes:
       - ./tapo.yaml:/app/tapo.yaml:ro
    ports:
      - 9333:9333
    environment:
      - TAPO_USER_EMAIL=YOUR@EMAIL.COM
      - TAPO_USER_PASSWORD=CHANGE_ME
      - TAPO_PROMETHEUS_PORT=9333 # optional
